<?php
/*
 * PagarmeCoreApiLib
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ).
 */

namespace PagarmeCoreApiLib\Models;

use JsonSerializable;

/**
 *Checkout card payment request
 */
class CreateCheckoutCreditCardPaymentRequest implements JsonSerializable
{
    /**
     * Card invoice text descriptor
     * @maps statement_descriptor
     * @var string|null $statementDescriptor public property
     */
    public $statementDescriptor;

    /**
     * Payment installment options
     * @var \PagarmeCoreApiLib\Models\CreateCheckoutCardInstallmentOptionRequest[]|null $installments public property
     */
    public $installments;

    /**
     * The payment authentication request
     * @var \PagarmeCoreApiLib\Models\CreatePaymentAuthenticationRequest|null $authentication public property
     */
    public $authentication;

    /**
     * Authorize and capture?
     * @var bool|null $capture public property
     */
    public $capture;

    /**
     * Define the type of one-off transaction initiated?
     * @var String|null $initiated_type public property
     */
    public $initiated_type;

    /**
     * Identifies the recurrence model
     * @var String $recurrence_model public property
     */
    public $recurrence_model;

    /**
     * Constructor to set initial or default values of member properties
     * @param string                             $statementDescriptor Initialization value for $this-
     *                                                                  >statementDescriptor
     * @param array                              $installments        Initialization value for $this->installments
     * @param CreatePaymentAuthenticationRequest $authentication      Initialization value for $this->authentication
     * @param bool                               $capture             Initialization value for $this->capture
     * @param String                             $initiated_type      Initialization value for $this->initiated_type
     * @param String                             $recurrence_model      Initialization value for $this->recurrence_model
     */
    public function __construct()
    {
        if (4 == func_num_args()) {
            $this->statementDescriptor = func_get_arg(0);
            $this->installments        = func_get_arg(1);
            $this->authentication      = func_get_arg(2);
            $this->capture             = func_get_arg(3);
            $this->initiated_type      = func_get_arg(4);
            $this->recurrence_model    = func_get_arg(5);
        }
    }


    /**
     * Encode this object to JSON
     */
    public function jsonSerialize()
    {
        $json = array();
        $json['statement_descriptor'] = $this->statementDescriptor;
        $json['installments']         = $this->installments;
        $json['authentication']       = $this->authentication;
        $json['capture']              = $this->capture;
        if($this->initiated_type) {
            $json['initiated_type'] = $this->initiated_type;
        }
        $json['recurrence_model']     = $this->recurrence_model;
        return $json;
    }
}
